### ISSUE TITLE
Left corner Logo

### ISSUE THREAD

**Issue by budap21** [NeejaViju/AccountX#13]
1. Correct left corner logo font
2. Left corner logo should filled completed to the top frame. Please refer attachement for rederence
[Logo issue.pdf](https://github.com/NeejaViju/AccountX/files/13259728/Logo.issue.pdf)

**Comment by NeejaViju** [comment]
logo fixed 
![image](https://github.com/NeejaViju/AccountX/assets/137764569/1d43e7d2-6aea-4a72-b708-bd136a2b0d80)
