### ISSUE TITLE
floating label under company profile for company ID, business trading name, legal name ,Mobile number ,business email and industry is missing

### ISSUE THREAD

**Issue by SuganthiRamaraj** [NeejaViju/AccountX#19]
Actual Output 
floating label under company profile for company ID, business trading name, legal name ,Mobile number ,business email and industry is missing
Also default value is loaded.
![image](https://github.com/NeejaViju/AccountX/assets/142293128/32d593b7-d9fd-4853-8d2f-011c2db4edf1)

Expected Output .

![image](https://github.com/NeejaViju/AccountX/assets/142293128/99a857dc-d2a2-4a26-99f8-6d8b93fffa58)

**Comment by NeejaViju** [comment]
fixed floating label for company label
