### ISSUE TITLE
GST Number- Input Data 

### ISSUE THREAD

**Issue by SuganthiRamaraj** [NeejaViju/AccountX#21]
GST Number Must have Alpha Numeric & it will not exceed for 15 digits. It should not get GST number more than 15 digits.

Actual output:
![image](https://github.com/NeejaViju/AccountX/assets/142293128/f449329f-f6b1-459d-87c8-fa04ed5a0d55)

**Comment by NeejaViju** [comment]
![image](https://github.com/NeejaViju/AccountX/assets/137764569/bb5b7407-fbf6-4fc8-8626-e59b744be36c)
fixed GST input
