### ISSUE TITLE
personal details-first name -position

### ISSUE THREAD

**Issue by Nalina87** [NeejaViju/AccountX#24]
<img width="261" alt="expected first name position in personal details" src="https://github.com/NeejaViju/AccountX/assets/142408131/a23c3e3a-3d3f-487e-a9fd-e6d926c96809">
<img width="353" alt="actual first name position in personal details" src="https://github.com/NeejaViju/AccountX/assets/142408131/429529db-d9d2-4295-a56a-8c318671bf74">

i have attached 2 screenshots. i have marked the issues. please compare them and fix the issues.
Please check the padding and change the position of the first name and floating label is not working in first name.

**Comment by Kklaks** [comment]
solved the issues.
