### ISSUE TITLE
Business legal information-position of all the fields are not in the correct position.

### ISSUE THREAD

**Issue by Nalina87** [NeejaViju/AccountX#26]
<img width="598" alt="actual upload field in bussiness legal information " src="https://github.com/NeejaViju/AccountX/assets/142408131/7f7d6f5c-cfbb-443c-acc2-e761a87ae9b7">
<img width="544" alt="expected upload fields position in business legal information" src="https://github.com/NeejaViju/AccountX/assets/142408131/3c68ac86-86bb-4bcb-92da-d087fdee982a">

please check the position of the each field, compare the screen shots and fix the issue.

**Comment by Kklaks** [comment]
positions fixed
