### ISSUE TITLE
Bank Account Details -Search symbol  at the right end is missing in Bank name 

### ISSUE THREAD

**Issue by SuganthiRamaraj** [NeejaViju/AccountX#31]
Search symbol  at the right end is missing in Bank name 

Expected  Output 

![image](https://github.com/NeejaViju/AccountX/assets/142293128/910dfcc6-8547-48b0-8116-2dc0764bfe4f)

Actual  Output 
![image](https://github.com/NeejaViju/AccountX/assets/142293128/d0a750c0-4b34-4ac5-b073-6b6788bc2f3a)

**Comment by Kklaks** [comment]
search icon added
